### ISSUE TITLE
Please update NuGet to support .NET Standard 1.3 or lower

### ISSUE THREAD

**Issue by tiksn** [sinkien/IBAN4Net#1]

**Comment by sinkien** [comment]
Hi, surely I'll look into it.

**Comment by ant-1** [comment]
@sinkien Can you provide a new nugget package using the current sources (1.0.7) ?
These two issues could be fixed https://github.com/sinkien/IBAN4Net/issues/9 https://github.com/sinkien/IBAN4Net/issues/10 with the last sources from your master branch.

**Comment by kubinko** [comment]
Any news about .NET Standard NuGet package? As we like this project and we needed a .NET Standard package, we cloned the git repo and created our own local NuGet package (for now). But it would be nice to have a package from original creator.

**Comment by sinkien** [comment]
Since version 2.0.0 this pacakge is based on netstandard (1.2, 1.4, 2.0). Latest published nuget (v2.0.3) contains that.
