### ISSUE TITLE
Please rename namespaces to start with capital letter

### ISSUE THREAD

**Issue by tiksn** [sinkien/IBAN4Net#2]

**Comment by sinkien** [comment]
Hi, is there any reason other than aesthetic :) ?

**Comment by tiksn** [comment]
Nope, it is just as C# developer we accustomed to have PascalCase-ed namespaces.

**Comment by sinkien** [comment]
Since version 2.0.0 the namespace has been fixed. Release and nuget package starting v 2.0.3 contains it.
